export const datamovie = [
	{
		id: '1',
		name: 'Inception',
		category: ['Sci-Fi'],
		duration: '148 minutes',
		madeIn: 'USA',
		suitableAge: 13,
		posters:
			'https://m.media-amazon.com/images/M/MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg',
		description: {
			director: 'Christopher Nolan',
			performer: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
			premiere: '2010-07-16',
		},
		content:
			'A thief who enters the dreams of others must perform an inception in order to erase his past crimes.',
		trailer: 'YoHD9XEInc0',
	},
	{
		id: '2',
		name: 'The Dark Knight',
		category: ['Action'],
		duration: '152 minutes',
		madeIn: 'USA',
		suitableAge: 13,
		posters: 'https://example.com/dark-knight-poster.jpg',
		description: {
			director: 'Christopher Nolan',
			performer: 'Christian Bale, Heath Ledger, Aaron Eckhart',
			premiere: '2008-07-18',
		},
		content: 'Batman must face the Joker, a criminal mastermind, as he tries to save Gotham City.',
		trailer: 'EXeTwQWrcwY',
	},
	{
		id: '3',
		name: 'Parasite',
		category: ['Thriller'],
		duration: '132 minutes',
		madeIn: 'South Korea',
		suitableAge: 15,
		posters: 'https://example.com/parasite-poster.jpg',
		description: {
			director: 'Bong Joon-ho',
			performer: 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
			premiere: '2019-05-30',
		},
		content:
			'A poor family schemes to become employed by a wealthy family by infiltrating their household.',
		trailer: '5xH0HfJHsaY',
	},
	{
		id: '4',
		name: 'The Matrix',
		category: ['Sci-Fi'],
		duration: '136 minutes',
		madeIn: 'USA',
		suitableAge: 15,
		posters: 'https://example.com/matrix-poster.jpg',
		description: {
			director: 'The Wachowskis',
			performer: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
			premiere: '1999-03-31',
		},
		content:
			'A hacker discovers the true nature of his reality and his role in the war against its controllers.',
		trailer: 'vKQi3bBA1y8',
	},
	{
		id: '5',
		name: 'Spirited Away',
		category: ['Animation'],
		duration: '125 minutes',
		madeIn: 'Japan',
		suitableAge: 10,
		posters: 'https://example.com/spirited-away-poster.jpg',
		description: {
			director: 'Hayao Miyazaki',
			performer: 'Rumi Hiiragi, Miyu Irino, Mari Natsuki',
			premiere: '2001-07-20',
		},
		content:
			'A young girl becomes trapped in a strange new world of spirits, and must find her way out.',
		trailer: 'ByXuk9QqQkk',
	},
];

export const moviesData = [
	{
		image: '/images/movies/ma-da.jpeg',
		title: 'MA DA (T16)',
		tags: ['Kinh Dị', "94'", 'Việt Nam', 'VN'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/69ZDBWoj5YM?si=mNUGtLgCGm51wrQs',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/conan-movie-27.png',
		title: 'THÁM TỬ LỪNG DANH CONAN (LT) 2D: NGÔI SAO 5 CÁNH 1 TRIỆU ĐÔ (T13)',
		tags: ['Hoạt hình', "111'", 'Nhật bản', 'Lồng Tiếng'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/69ZDBWoj5YM?si=mNUGtLgCGm51wrQs',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/dep-trai-thay-sai-sai.jpeg',
		title: 'ĐẸP TRAI...THẤY SAI SAI (T18) 2D PĐ',
		tags: ['Phim Hài', "101'", 'Hàn Quốc', 'Phụ Đề'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/blue-lock.png',
		title: 'BLUE LOCK: EPISODE NAGI (K)',
		tags: ['Hoạt Hình, Anime, Tâm Lý', "90'", 'Nhật bản', 'Phụ Đề'],
		rating: 'K',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/bay.png',
		title: 'BẪY (T16)',
		tags: ['Hành Động, Tâm Lý, Kinh Dị', "105'", 'Khác', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/tieng-goi-tu-dia-nguc.jpeg',
		title: 'TIẾNG GỌI TỪ ĐỊA NGỤC (T16)',
		tags: ['Kinh Dị', "92'", 'Khác', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/chay-dua-voi-tu-than.jpeg',
		title: 'CHẠY ĐUA VỚI TỬ THẦN (T16)',
		tags: ['Hồi Hộp, Hành Động', "90'", 'Hàn Quốc', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/deadpool-va-wolverine.png',
		title: 'DEADPOOL VÀ WOLVERINE 2D (T18)',
		tags: ['Siêu Anh Hùng, Hành Động', "127'", 'Mỹ', 'Phụ Đề'],
		rating: 'T18',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/oan-hon-bao-an.jpeg',
		title: 'OAN HỒN BÁO OÁN (T18)',
		tags: ['Kinh Dị', "100'", 'Khác', 'Phụ Đề'],
		rating: 'T18',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/vu-be-boi-anh-trang.jpeg',
		title: 'VỤ BÊ BỐI ÁNH TRĂNG (T16)',
		tags: ['Tình Cảm, Phim Hài', "132'", 'Mỹ', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/mo-tra-tan-sneakshow.jpeg',
		title: 'MỒ TRA TẤN (T18)',
		tags: ['Kinh Dị', "81'", 'Khác', 'Phụ Đề'],
		rating: 'T18',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-10',
		onGoing: true,
	},
	{
		image: '/images/movies/bi-mat-ban-nhac-an-giau.jpeg',
		title: 'BÍ MẬT: BẢN NHẠC ẨN DẤU (K)',
		tags: ['Tình Cảm, Tâm Lý', "115'", 'Nhật Bản', 'Phụ Đề'],
		rating: 'K',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-23',
		onGoing: false,
	},
	{
		image: '/images/movies/da-nu-bao-thu.jpeg',
		title: 'ĐẢ NỮ BÁO THÙ (T16)',
		tags: ['Hành Động', "99'", 'Hàn Quốc', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-23',
		onGoing: false,
	},
	{
		image: '/images/movies/gieng-quy.png',
		title: 'GIẾNG QUỶ (T18)',
		tags: ['Kinh Dị', "99'", 'Khác', 'Phụ Đề'],
		rating: 'T18',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-23',
		onGoing: false,
	},
	{
		image: '/images/movies/borderlands.jpeg',
		title: 'BORDERLANDS: TRỞ LẠI PANDORA (T13)',
		tags: ['Hành Động', "99'", 'Nhật Bản', 'Phụ Đề'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-23',
		onGoing: false,
	},
	{
		image: '/images/movies/harold.jpeg',
		title: 'HAROLD & CÂY BÚT PHÉP THUẬT 2D PĐ (T13)',
		tags: ['Phim Hài, Phiêu Lưu', "99'", 'Khác', 'Phụ Đề'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-23',
		onGoing: false,
	},
	{
		image: '/images/movies/am-duong-su.png',
		title: 'ÂM DƯƠNG SƯ: 0 - KHỞI NGUỒN (T16)',
		tags: ['Thần Thoại', "113'", 'Nhật Bản', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-23',
		onGoing: false,
	},
	{
		image: '/images/movies/hai-muoi.png',
		title: 'HAI MUỐI (K)',
		tags: ['Tình Cảm, Gia Đình', "99'", 'Việt Nam', 'VN'],
		rating: 'K',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-30',
		onGoing: false,
	},
	{
		image: '/images/movies/chang-nu-phi-cong.jpeg',
		title: 'CHÀNG NỮ PHI CÔNG (T13)',
		tags: ['Phim Hài', "110'", 'Hàn Quốc', 'Phụ Đề'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-30',
		onGoing: false,
	},
	{
		image: '/images/movies/lam-giau-voi-ma.jpeg',
		title: 'LÀM GIÀU VỚI MA (T13)',
		tags: ['Phim Hài, Tâm Lý', "99'", 'Việt Nam', 'VN'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-30',
		onGoing: false,
	},
	{
		image: '/images/movies/hellboy.jpeg',
		title: 'HELLBOY: ĐẠI CHIẾN QUỶ DỮ (T18)',
		tags: ['Kinh Dị', "99'", 'Khác', 'Phụ Đề'],
		rating: 'T18',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-10-30',
		onGoing: false,
	},
	{
		image: '/images/movies/beetle-juice-ma-sieu-quay.jpeg',
		title: 'MA SIÊU QUẬY (T13)',
		tags: ['Phim Hài, Khoa Học Viễn Tưởng, Kinh Dị', "99'", 'Khác', 'Phụ Đề'],
		rating: 'T13',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-11-06',
		onGoing: false,
	},
	{
		image: '/images/movies/khong-noi-dieu-du.jpeg',
		title: 'KHÔNG NÓI ĐIỀU DỮ (T16)',
		tags: ['Kinh Dị', "99'", 'Khác', 'Phụ Đề'],
		rating: 'T16',
		url: 'https://www.youtube.com/embed/YjWrLPr8_2A?si=ExVRjNyxkIiDMneM',
		releaseDate: '2024-11-13',
		onGoing: false,
	},
];

export const theater = [
	{
		name: 'Quốc Thanh',
		address: '271 Nguyễn Trãi, Phường Nguyễn Cư Trinh, Quận 1, Thành Phố Hồ Chí Minh',
		type: 'theater',
		image: '/images/theater/Quoc_Thanh.jpg',
		room: '6',
		chair: '930',
		status: 'open',
	},
	{
		name: 'Đà Lạt',
		address: 'Quảng trường Lâm Viên, P10, TP.Đà Lạt, Lâm Đồng',
		type: 'theater',
		image: '/images/theater/Da_Lat.jpg',
		room: '6',
		chair: '1592',
		status: 'open',
	},
	{
		name: 'Hai Bà Trưng (TP.HCM)',
		address: '135 Hai Bà Trưng, Phường Bến Nghé ,Quận 1, Thành Phố Hồ Chí Minh',
		type: 'theater',
		image: '/images/theater/Hai-Ba-Trung.jpg',
		room: '5',
		chair: '725',
		status: 'open',
	},
	{
		name: 'Huế',
		address: '25 Hai Bà Trưng, Vĩnh Ninh, Thành phố Huế, Thừa Thiên Huế',
		type: 'theater',
		image: '/images/theater/Hue.jpg',
		room: '8',
		chair: '1200',
		status: 'open',
	},
	{
		name: 'Sinh Viên (Bình Dương)',
		address: 'Nhà văn hóa sinh viên, Đại học Quốc gia HCM, P.Đông Hòa, Dĩ An, Bình Dương',
		type: 'theater',
		image: '/images/theater/Sinh-Vien.jpg',
		room: '4',
		chair: '881',
		status: 'open',
	},
	{
		name: 'Mỹ Tho',
		address: '52 Đinh Bộ Lĩnh, Phường 3, Thành phố Mỹ Tho, Tiền Giang',
		type: 'theater',
		image: '/images/theater/My-Tho.jpg',
		room: '5',
		chair: '912',
		status: 'open',
	},
	{
		name: 'Kiên Giang',
		address:
			'Lô A2 - Khu 2 Trung tâm Thương mại Rạch Sỏi, Đường Nguyễn Chí Thanh, Phường Rạch Sỏi, Thành phố Rạch Giá, Tỉnh Kiên Giang',
		type: 'theater',
		image: '/images/theater/Kien-Giang.jpg',
		room: '4',
		chair: '750',
		status: 'open',
	},
	{
		name: 'Lâm Đồng',
		address: '713 QL20, Liên Nghĩa, Đức Trọng, Lâm Đồng',
		type: 'theater',
		image: '/images/theater/Lam-Dong.jpg',
		room: '4',
		chair: '853',
		status: 'open',
	},
	{
		name: 'Gym/Kidzone',
		image: '/images/theater/Gym_Kidzone.jpg',
	},
	{
		name: '',
		type: 'theater',
		image: '/images/theater/Hiep_Phu.jpg',
		status: 'comingsoon',
	},
	{
		name: 'TRỤ SỞ | HEADQUARTER',
		address: '135 Hai Bà Trưng, Phường Bến Nghé, Quận 1',
		type: 'headquarter',
		image: '/images/theater/Tru_So.jpg',
		status: 'open',
		mail: 'marketing.cinestar@gmail.com',
		phone: '028 7300 7279',
	},
];
